sudo: false
language: ruby
services:
  - docker
before_install:
  - git clone --depth 1 https://github.com/seiferma/Docker_BuildUtils.git /tmp/BuildUtils
  - . /tmp/BuildUtils/travisSetup.sh
script:
  - travisBuildDockerhub.sh
deploy:
  provider: script
  script: travisDeployDockerhub.sh
  on:
    branch: master
env:
  global: 
    - IMAGE_NAME=seiferma/nextcloud
    - secure: "QbkfzfpFQX3xOgHo795Jsx07eKfyXWaGTHj3ZvNMCMHqmf1W7y3LicG7tDcIqaRM8PTLia7/qc+WYN2gGU+2xazAC35DF/YfZ6Dvi8V4sSfGXJMXRQLclxs3BKohAoLHPMSMAzjucysb807y4CAJ6xC3dC4cInY6PA9nZPCXpDoxN86gE3/KCuF8dqTqot48Bm3s01J3nqRq6JXkroLIeynyp1mnLbc7HL3ZWQjpI+4Ihqhup4N1yV01/zHbP9A1INpR/vZDUMULa+aiSez1Pag6OopAXV3zeoZIX23QYvDMCJoljD6oLMciTIzBzC2r1M/mu5ztQ0vm+qTYWEnsZwG81I4iAiXXKmoL3KY/QTvPd6b2qGKBGa+NFhhmSDa7DfH6huQhLscGD4r5kbliDjvzILcCcf03yOKV47MI8whigxPIt0SDkMy3lFv9Eq4rfTp2zgsquHes+subBClQsJT014fhlABGqCoDoLNSWmdCQIkvgaRVyXbP0OcrKJIuP4j9ZaDZD5hs3pEYSSCdLQ5H6sriKPXoz3bHwBI/Xb1WnLd9WtrzwreRGZaZDn4eUuWNJNZVArOhdC4xRabx1xCL6zy0I92iK4F/6waGfoqox4iMQzSKCavZ0Yi0qO3Jvnq1iDKsn/WaM22kRo6Gx6iVVEzATZO2aWMJGs147fk="
